import Head from 'next/head'
import styles from './page.module.scss'
import Image from 'next/image'
import Script from 'next/script'
import { useRouter } from 'next/router'
import Link from 'next/link'


export function Button({ text, disabled = false }) {
  return <div className={`${styles.button} ${disabled ? styles.button_disabled : ''}`}>
    {text}
  </div>
}


export function Radio({ checked, disabled = false }) {
  return <div className={`${styles.radio} ${disabled ? styles.radio_disabled : ''}`}>
    <div className={`${styles.radio__outer} ${checked ? styles.radio__outer_checked : ''}`}>
      {checked && <div className={styles.radio__dot}></div>}
    </div>
  </div>
}

export function RadioBox({ text, checked, disabled }) {
  return <div className={styles.radioBox}>
    <Radio checked={checked} disabled={disabled} />
    <div className={styles.radioBox__text}>{text}</div>
  </div>
}

export function ImageWithText({ src, text }) {
  return <div className={styles.imageWithText}>
    <div className={styles.imageWithText__image}>
      <Image src={src} width={48} height={48} />
    </div>
    <div className={styles.imageWithText__text}>
      {text}
    </div>
  </div>
}

export function Question({ src, text, answers }) {
  return <div className={styles.question}>
    <div className={styles.question__image}>
      {src && <Image src={src} width={600} height={400} />}
    </div>
    <div className={styles.question__text}>{text}</div>
    <div className={styles.question__answers}>
      {answers.map((answer, index) => {
        return <div key={index}>
          <RadioBox text={answer.value} checked={false} disabled={false} />
        </div>
      })}
    </div>
  </div>
}


export default function Home() {
  
  const router = useRouter();
    //const id=router.query.page
    const onClickHandler = async () => {   
        let user_info = penalty_point_and_json_format()
    
        const responce = await fetch('/api/exampledb', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json;charset=utf-8' },
          body: JSON.stringify({
           user_info,
          })
        })
        document.location.replace('result')
        const data = await responce.json();
        console.log(data);
      }

  const { page } = router.query

  const test = {
    title: 'Очень важный тест',
    timeLimit: 3600,
    mode: 'random',
    questions: [
      {
        title: 'Чему равно выражение 2 + 2?',
        timeLimit: 60,
        content: [
          {
            type: 'image',
            src: '/images/map.png'
          }
        ],
        type: 'radio',
        answers: [
          {
            value: 'Один 1',
            valid: true,
          },
          {
            value: 'Два 2',
            valid: false,
          },
          {
            value: 'Три',
            valid: false,
          },
          {
            value: 'Четыре',
            valid: false,
          },
          {
            value: 'Три',
            valid: false,
          },
          {
            value: 'Четыре',
            valid: false,
          },
        ]
      },
    ]
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.page}>
      <Script src="script.js" />
         <div onClick={()=>start()}>Начать тест</div>
         <div onClick={onClickHandler} > Закончить тест/Отправить данные</div>
        <div className={styles.page__header}>
          <div className={styles.page__info}>
            <ImageWithText src={'/images/question.svg'} text={'8/' + test.questions.length} />
            <ImageWithText src={'/images/time.svg'} text={'60:00'} />
          </div>
          <div className={styles.page__title}>
            {test.title}
          </div>
          <div className={styles.page__logo}>
            Логотип {page}
          </div>

        </div>
        <div className={styles.page__body}>
          <div className={styles.page__content}>
            <Question
              src={test.questions[0].content[0].src}
              text={test.questions[0].title}
              answers={test.questions[0].answers}
            />
          </div>
          <div className={styles.page__controls}>
            <Button text={'Пропустить'} />
            <Button text={'Ответить'} />
          </div>
        </div>
      </div>
    </div>
  )
}
