import Head from 'next/head'
import styles from './index.module.scss'
import Script from 'next/script'
import Link from 'next/link'

export default function Home() {
  const onClickHandler = async () => {    
    
    let user_info = penalty_point_and_json_format()

    const responce = await fetch('/api/exampledb', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json;charset=utf-8' },
      body: JSON.stringify({
       user_info,
      })
    })
    const data = await responce.json();
    console.log(data);
  }


  return (
    
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="script.js" />
      <div className={styles.main}>

        <h2>Кнопки</h2>
        <div>
          <Button text={'Создать игру'} disabled />
          <Button text={'Создать игру'} />
        </div>
        <div onClick={onClickHandler}>Нажми сюда</div>

        <h2>Radio</h2>
        <div>
          <Radio checked disabled={false} />
          <Radio checked={false} disabled={false} />
          <Radio checked={false} disabled={true} />
          <Radio checked={true} disabled={true} />
        </div>

        <h2>RadioBox</h2>
        <div>
          <RadioBox text={'Вариант ответа'} />
        </div>

      </div>
    </div>
  )
}








export function Button({ text, disabled = false }) {
  return <div className={`${styles.button} ${disabled ? styles.button_disabled : ''}`}>
    {text}
  </div>
}


export function Radio({ checked, disabled = false }) {
  return <div className={`${styles.radio} ${disabled ? styles.radio_disabled : ''}`}>
    <div className={`${styles.radio__outer} ${checked ? styles.radio__outer_checked : ''}`}>
      {checked && <div className={styles.radio__dot}></div>}
    </div>
  </div>
}

export function RadioBox({ text, checked, disabled }) {
  return <div className={styles.radioBox}>
    <Radio checked={checked} disabled={disabled} />
    <div className={styles.radioBox__text}>{text}</div>
  </div>
}